
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: community-labeler

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: ./
        name: Label issue or pull request
        with:
          label_name: community
          label_color: 5319E7
          org_membership: puppetlabs
          token: ${{ secrets.GITHUB_TOKEN }}
